In [1]:
import numpy as np
import pandas as pd

### Задание 1.1

In [2]:
a = np.array([[1,6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 1.2

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 1.3

In [5]:
b = a_centered[:, :1].copy().flatten()
c = a_centered[:, -1].copy()
a_centered_sp = b @ c
a_centered_sp

8.0

In [6]:
N = a.shape[0]
N

5

In [7]:
res = a_centered_sp / (N-1)
res

2.0

### Задание 1.4

In [8]:
at = a.T
res2 = np.cov(at)[0, 1]
res2

2.0

In [9]:
res == res2

True

### Задание 2.1

In [10]:
autors = pd.DataFrame({'autor_id':[1, 2, 3], 'autor_name':['Тургеньев', 'Чехов', 'Островской']})
autors

autor_id  autor_name
0         1   Тургеньев
1         2       Чехов
2         3  Островской

In [11]:
book = pd.DataFrame({'autor_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 
                                   'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]})


### Задание 2.2

In [12]:
authors_price = pd.merge(autors, book, on = 'autor_id')
authors_price

autor_id  autor_name            book_title  price
0         1   Тургеньев           Отцы и дети    450
1         1   Тургеньев                 Рудин    300
2         1   Тургеньев     Дворянское гнездо    350
3         2       Чехов      Толстый и тонкий    500
4         2       Чехов       Дама с собачкой    450
5         3  Островской                 Гроза    370
6         3  Островской  Таланты и поклонники    290

### Задание 2.3

In [13]:
top5 = authors_price.sort_values(by = 'price', ascending = False)
top5.head()

autor_id  autor_name         book_title  price
3         2       Чехов   Толстый и тонкий    500
0         1   Тургеньев        Отцы и дети    450
4         2       Чехов    Дама с собачкой    450
5         3  Островской              Гроза    370
2         1   Тургеньев  Дворянское гнездо    350

### Задание 2.4

In [14]:
authors_price['min_price'] = authors_price.apply(lambda x: x['price'], axis = 1)
authors_price['max_price'] = authors_price.apply(lambda x: x['price'], axis = 1)
authors_price['mean_price'] = authors_price.apply(lambda x: x['price'], axis = 1)
authors_price

autor_id  autor_name            book_title  price  min_price  max_price  \
0         1   Тургеньев           Отцы и дети    450        450        450   
1         1   Тургеньев                 Рудин    300        300        300   
2         1   Тургеньев     Дворянское гнездо    350        350        350   
3         2       Чехов      Толстый и тонкий    500        500        500   
4         2       Чехов       Дама с собачкой    450        450        450   
5         3  Островской                 Гроза    370        370        370   
6         3  Островской  Таланты и поклонники    290        290        290   

   mean_price  
0         450  
1         300  
2         350  
3         500  
4         450  
5         370  
6         290

In [15]:
authors_stat = authors_price.groupby('autor_name').agg({'min_price': 'min', 'max_price': 'max', 'mean_price': 'mean'})
authors_stat

min_price  max_price  mean_price
autor_name                                  
Островской        290        370  330.000000
Тургеньев         300        450  366.666667
Чехов             450        500  475.000000